services:
- type: web
  name: nginx-reverse-proxy
  env: docker
  repo: https://github.com/Amrit0991/nginx-reverse-proxy-docker
  plan: standard
  healthCheckPath: /heartbeat
  - key: PROXY_PASS
    value: https://metto.studio
